# Generated by Django 3.0.1 on 2020-02-07 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('Caption', models.CharField(max_length=500)),
                ('File', models.FileField(null=True, upload_to='profile/photos/')),
                ('like', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='Hello', max_length=660)),
                ('post', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='post.Post')),
            ],
        ),
    ]
