# Generated by Django 3.0.1 on 2020-01-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200113_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='File',
            field=models.FileField(upload_to='profile/pics/'),
        ),
    ]
