# Generated by Django 3.0.1 on 2020-01-22 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20200113_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('images', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='post.Post')),
            ],
        ),
    ]
