# Generated by Django 3.0.1 on 2020-01-22 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='images',
            new_name='image',
        ),
    ]
