# Generated by Django 3.0.1 on 2020-01-23 06:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0006_auto_20200122_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_owner',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
