# Generated by Django 3.0.1 on 2020-01-23 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_comment_comment_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
