# Generated by Django 3.0.1 on 2020-01-30 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_comment_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
